# NOTE: This `pipeline.yml` file is saved in the WebUI.
# Editing it here has no effect, we simply include this
# to keep track of what is implemented in the WebUI!
steps:
  # In the WebUI, the `cryptic` launch job _must_ be the first job to run
  - label: ":rocket: launch pipelines"
    plugins:
      # This gives us the SSH key that allows us to clone our private packages
      - staticfloat/ssh-agent:
          keyvars:
            - "GITHUB_SSH_KEY"
      - staticfloat/cryptic#v2:
          unsigned_pipelines:
            - .buildkite/runtests.yml
    command: "true"
    agents:
      sandbox.jl: true
    env:
      CRYPTIC_ADHOC_SECRET_GITHUB_SSH_KEY: "oYKA8G0WZjWZSlOI2oUgjz5Jt1l4bkCD0PY6hzzqAvrEklr1ywW/j/0H/PTUGuc0Th01Sp5mcLOP3o2vM6i9keHKahfL+Nt7WRxm74njkSZlSeMTIOTZnW5HNkh+mtDU8J+v0NzpEkZSAunV9InGSKSCKjjOoBW3vMnQeF+rjSlNz+WPOVHUf7JF/PMO72tlLOg2/okINOY8h7wGXIAlIt35P9be2z2A+ldlE+9leGzPGtKHEE2dU+8rCvsAonL6kWKWgj+8nk+rknAtQ2SBy2cmpzPa58pKbc6fNQ/GIZDrGoyIErSu7TX2Z6eoWZo+liW4wYQjtYJHKd+k5hJHDA==;U2FsdGVkX18ZUgQ5F339pNVWgzdNB59jzBe4SZgTdRcdTs1QxPlepuoryEodYOLkvTtqZWjoFDg1siJ9BXTcv89wvkQrhPGVb86vJsdbZkMLQKHFX4DXV2yQpsM6ETeYym5OlvVRg0G6nflHFjapuGetGOHZnD2gLDUOFqNM6ADoMlg3bLEvylkmqeucvvl38r7OAQEDSrwdyF0QBXcMoU84STIDEmauFyJHDH/5x0SdasUL+AdB6cX+a6X/B7sazEZcWgb1+wYRcmc1fOKbwIrVw2A4qIR03vP5nSyaXhdTCruDwro0/2y+1dXmB24IIFtaqKIGPwsDYZZnZkBvJrjaMxtaXGENoID7JmYX8mQmZV9Jy0QRXMX1Gw5d/uwefY7egX8h549uPJUWlGR8QIDcr5p9HSYTktvSIl7ic8us2YmDHUmCsQXD8ewL2ccNCUwEoL8gNjYO+uL3HFZtVGU2kCth6X+3sXHwlRd4WHFjG4wWbbD+56nQv6ICtIqbPdUzchyZ9Rlw9yctB1CTgnKWS8wue564Wq05l8tPM7iYSwWAtSHi1rPf5Q1Yy68AWMwEpkPT76/sk1TQWDCOpTPOzqMpdp6NCIsGCSBWk71KoV0eHq3cN8bRZXcOPiGSiafBm13VKRxDBIU52YIObfBgzUBhN2RcDFocXhkLffYjhji5lfdqVZB4g7i5sDQO4nFSxCcUtitwiqbDEOlbExHYZ4oPXFRzow9yqIxlNLLfNTJ6COv96yizzy89ZgAW8Ka1mfza6zVeTnsJoCxwxWZdwmtdxhtjcq63YdkZgbQSpUJdLeJpkVe1yokSSQYtIJzk8X1dQEG27ag5PBhE7d0d/jBOyyaFg+vNxRKbsc9d69jIE5UDZu0igt/ZlMEj6B82f3tQJnrJ8ljC/aeWVeWtOfdtdjgTJoKO3tBVUGC7Yfpre5K1Cd8aujPu7TCkE7gCFAsJ8LC8dhK75vQG4jfg9R7QRLUWQ5ZKxQIwodDx32AkizEyUWXgJk8K7BxW"
