steps:
  - label: "BSIM4 tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "https://jc-cedarsim-juliabuilds.s3.amazonaws.com/vanilla/julia-latest-linux-x86_64.tar.gz"
      - JuliaCI/julia-test#v1:
          extra_registries: https://github.com/CedarEDA/PublicRegistry.git
    agents:
      os: "linux"
      arch: "x86_64"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120


  - label: "BSIM4 tests (Julia nightly)"
    soft_fail: true
    plugins:
      - JuliaCI/julia#v1:
          version: nightly
      - JuliaCI/julia-test#v1:
          extra_registries: https://github.com/CedarEDA/PublicRegistry.git
    agents:
      os: "linux"
      arch: "x86_64"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120


  - group: ":arrow_right: Downstream testing"
    notify:
      - github_commit_status:
          context: "Downstream"
    steps:
      - label: ":runner: CedarSim"
        plugins:
          - JuliaCI/julia#v1:
              version: "https://jc-cedarsim-juliabuilds.s3.amazonaws.com/vanilla/julia-latest-linux-x86_64.tar.gz"
          - JuliaCI/julia-test#v1:
                run_tests: false
                extra_registries: https://github.com/CedarEDA/PublicRegistry.git
          - staticfloat/metahook:
              pre-command: |
                echo "--- Clone CedarSim"
                git clone https://github.com/CedarEDA/CedarSim.jl.git CedarSim

                echo "--- Prepare CedarSim to use the current version of all packages for testing"
                JULIA_PKG_PRECOMPILE_AUTO=0 \
                julia --project=CedarSim -e 'import Pkg; Pkg.instantiate(); \
                                                         Pkg.develop(path="."); \
                                                         Pkg.precompile();'
        commands: |
          cd CedarSim
          julia --project=. -e 'import Pkg; Pkg.test()'
        agents:
          os: "linux"
          arch: "x86_64"

      # - label: ":runner: CedarEDA"
      #   plugins:
      #     - JuliaCI/julia#v1:
      #         version: "https://jc-cedarsim-juliabuilds.s3.amazonaws.com/vanilla/julia-latest-linux-x86_64.tar.gz"
      #     - JuliaCI/julia-test#v1:
      #           run_tests: false
      #           extra_registries: https://github.com/JuliaComputing/CedarEDARegistry.git,ssh://git@github.com/JuliaComputing/JuliaSimRegistry.git
      #     - staticfloat/metahook:
      #         pre-command: |
      #           echo "--- Clone CedarEDA"
      #           git clone https://github.com/CedarEDA/CedarEDA.jl.git CedarEDA

      #           echo "--- Prepare CedarEDA to use the current version of all packages for testing"
      #           JULIA_PKG_PRECOMPILE_AUTO=0 JULIA_PKG_USE_CLI_GIT=true \
      #           julia --project=CedarEDA -e 'import Pkg; Pkg.instantiate(); \
      #                                                    Pkg.develop(path="."); \
      #                                                    Pkg.precompile();'
      #   commands: |
      #     cd CedarEDA
      #     julia --project=. -e 'import Pkg; Pkg.test()'
      #   agents:
      #     os: "linux"
      #     arch: "x86_64"
